[workspace]

members = [
    "core",
    "nlprule",
    "request"
]

# [profile.release] # BUILD_BINDINGS_UNCOMMENT
# lto = "fat" # BUILD_BINDINGS_UNCOMMENT
# codegen-units = 1 # BUILD_BINDINGS_UNCOMMENT