[workspace]
members = [
    "core",
    "nlprule",
    "request"
]

# nlprule is really slow without optimizations (esp. compiling binaries)
[profile.dev]
opt-level = 2
build-override = { opt-level = 2 }